api_platform:
    title: 'Blizy Smartphone Price Comparison API'
    description: 'API for scraped smartphone data with price comparison and search capabilities'
    version: 1.0.0
    
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Model' 
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
    collection:
        pagination:
            enabled: true
            items_per_page_parameter_name: 'itemsPerPage'
            page_parameter_name: 'page'
            enabled_parameter_name: 'pagination'
            partial_parameter_name: 'partial'
