doctrine:
    dbal:
        # configure these for your database server
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'  # pdo_mysql driver is compatible with MariaDB
                server_version: '%env(resolve:MYSQL_VERSION)%'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                # https://symfony.com/doc/current/messenger.html#doctrine-transport
                schema_filter: '~^(?!messenger_messages)~'
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types:
                    enum: string
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            logging: false
